services:
  wallet-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: wallet-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    environment:
      APP_ENV: local
      PHP_IDE_CONFIG: "serverName=wallet-app"
    depends_on:
      - wallet-db
      - wallet-redis

  wallet-worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: wallet-worker
    working_dir: /var/www/html
    command: sh -lc "php artisan queue:work --tries=3 --timeout=90"
    volumes:
      - ./src:/var/www/html
    environment:
      APP_ENV: local
    depends_on:
      - wallet-db
      - wallet-redis

  wallet-nginx:
    image: nginx:alpine
    container_name: wallet-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wallet-app

  wallet-db:
    image: mysql:8.4
    container_name: wallet-db
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_USER: wallet
      MYSQL_PASSWORD: wallet
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wallet", "-pwallet" ]
      interval: 10s
      timeout: 5s
      retries: 10

  wallet-redis:
    image: redis:7-alpine
    container_name: wallet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: